<a href="https://colab.research.google.com/github/AndreiTugaoen/58013-Linear-Algebra/blob/main/Laboratory_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([
              [1, 4],
              [0, 3]])
np.linalg.det(A)

3.0000000000000004

In [3]:
import numpy as np

B = np.array([
              [1, 3, 5, 6],
              [0, 3, 1, 3],
              [3, 1, 8, 2],
              [5, 2, 6, 8]])
np.linalg.det(B)

-235.0000000000002

Associative Property

In [44]:
import numpy as np

A = np.array([[11, 22, 33],
              [44, 55, 66],
              [77, 88, 99]])

B = np.array([[8, 8, 7],
              [0, 1, 4],
              [2, 2, 0]])

C = np.array([[3, 0, 1],
              [6, 1, 2],
              [1, 1, 0]])

#(A * B) * C = A * (B * C)
left = np.dot(np.dot(A, B), C)
right = np.dot(A, np.dot(B, C))
print("Left","\n", left)
print("Right", "\n", right)

assert np.array_equal(left, right), "Error"
print("Associative Property is true")


Left 
 [[1683  341  506]
 [5214 1067 1562]
 [8745 1793 2618]]
Right 
 [[1683  341  506]
 [5214 1067 1562]
 [8745 1793 2618]]
Associative Property is true


Distributive Property

In [45]:
import numpy as np

A = np.array([[0, 2, 3],
              [5, 5, 6],
              [1, 7, 19]])

B = np.array([[1, 2, 3],
              [6, 5, 4],
              [9, 8, 7]])

C = np.array([[5, 4, 3],
              [2, 1, 0],
              [6, 7, 8]])

#A * (B + C) = A * B + A * C
left = np.dot(A, (B + C))
right = np.dot(A, B) + np.dot(A, C)
print("Left","\n", left)
print("Right", "\n", right)

assert np.array_equal(left, right), "Error"
print("Distributive Property is true")


Left 
 [[ 61  57  53]
 [160 150 140]
 [347 333 319]]
Right 
 [[ 61  57  53]
 [160 150 140]
 [347 333 319]]
Distributive Property is true


Closure Property

In [46]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 0, 9],
              [7, 1, 4],
              [3, 3, 1]])

#The result of the matrix multiplication is also a matrix
result = np.dot(A, B)
print(result)

assert result.shape == (3, 3), "Error"
print("Closure Property is true")


[[ 32  11  20]
 [ 89  23  62]
 [146  35 104]]
Closure Property is true


Identity Property

In [47]:
import numpy as np

A = np.array([[11, 25, 3],
              [4, 2, 61],
              [7, 78, 49]])

#A * I = A, where I is the identity matrix
I = np.eye(3)
identity = np.dot(A , I)
print(identity)

assert np.array_equal(identity, A), "Error"
print("Identity Property is true")


[[11. 25.  3.]
 [ 4.  2. 61.]
 [ 7. 78. 49.]]
Identity Property is true


Zero Property

In [48]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#A * 0 = 0, where 0 is the zero matrix
matrix = np.zeros((3, 3))
zero = np.dot(A, matrix)
print(zero)

assert np.array_equal(zero, matrix), "Error"
print("Zero Property is true")


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Zero Property is true


Scalar Property

In [49]:
import numpy as np

A = np.array([[13, 0, 2],
              [8, 5, 6],
              [74, 28, 1]])

#k * (A * B) = (k * A) * B = A * (k * B)
k = 2
left = k * A
right = A * k
print("Left","\n", left)
print("Right", "\n", right)

assert np.array_equal(left, right), "Error"
print("Scalar Property is true")


Left 
 [[ 26   0   4]
 [ 16  10  12]
 [148  56   2]]
Right 
 [[ 26   0   4]
 [ 16  10  12]
 [148  56   2]]
Scalar Property is true
