<a href="https://colab.research.google.com/github/AndreiTugaoen/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [18]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

#a: AB
#Print the result for a
a = np.dot(A, B)
print("a: AB")
print(a)

#b: D + D
#Print the result for b
b = D + D
print("\nb: D + D")
print(b)

#c: 2C
#Print the result for c
c = 2 * C
print("\nc: 2C")
print(c)

a: AB
[[22 28]
 [49 64]]

b: D + D
[[2 4]
 [6 8]]

c: 2C
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2

In [20]:
A = [2, 7, 4]
B = [3, 9, 8]

#Computing for the cross-product manually
Cross = [A[1] * B[2] - A[2] * B[1],
          A[2] * B[0] - A[0] * B[2],
          A[0] * B[1] - A[1] * B[0]]

print("The cross product of A and B is:")
print(Cross)

The cross product of A and B is:
[20, -4, -3]
