<a href="https://colab.research.google.com/github/AndreiTugaoen/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [5]:
#Coding Activity 10
import numpy as np

coef = np.array([[30, 10, 120],
                         [40, 20, 200],
                         [50, 40, 360]])

const = np.array([12500, 18000, 25700])


F_price, Y_price, E_price = np.linalg.solve(coef, const)

print(f"The price of one sack of flour is {F_price:.2f} pesos.")
print(f"The price of one pack of yeast is {Y_price:.2f} pesos.")
print(f"The price of one egg is {E_price:.2f} pesos.")

The price of one sack of flour is 330.00 pesos.
The price of one pack of yeast is 140.00 pesos.
The price of one egg is 10.00 pesos.
