<a href="https://colab.research.google.com/github/AndreiTugaoen/58013-Linear-Algebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np


A = np.array([[-0.4], [4.3], [-0.6]])
B = np.array([[-0.2, 0.2, 0.1]])
C = np.array([[-0.2, 2.1, -1.5]])


add = A + B

sub = A - B

dotpro = np.dot(B, C.T)

cross = np.cross(B, C)


print("Vector A:\n", A)
print("\nVector B:\n", B)
print("\nVector C:\n", C)
print("\nVector Addition (A + B):\n", add)
print("\nVector Subriction (A - B):\n", sub)
print("\nVector Dot Product (B . C):\n", dotpro)
print("\nVector Cross Product (B x C):\n", cross)


Vector A:
 [[-0.4]
 [ 4.3]
 [-0.6]]

Vector B:
 [[-0.2  0.2  0.1]]

Vector C:
 [[-0.2  2.1 -1.5]]

Vector Addition (A + B):
 [[-0.6 -0.2 -0.3]
 [ 4.1  4.5  4.4]
 [-0.8 -0.4 -0.5]]

Vector Subriction (A - B):
 [[-0.2 -0.6 -0.5]
 [ 4.5  4.1  4.2]
 [-0.4 -0.8 -0.7]]

Vector Dot Product (B . C):
 [[0.31]]

Vector Cross Product (B x C):
 [[-0.51 -0.32 -0.38]]
