<a href="https://colab.research.google.com/github/AndreiTugaoen/58013-Linear-Algebra/blob/main/Vector_Spaces_and_Operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector

In [1]:
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [13]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

print(ball1)
print(ball2)
#ball = np.shape([[ball1], [ball2]])
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls

print(z)
x= np.ndim

[1 2 3]
[ 0  1 -1]
(3, 3)


Spaces and Additions

In [14]:
#Addition
import numpy as np

B = np.array([4,3])
B = np.array([2, -5])
R = A + B
print(R)

[ 6 -2]


In [15]:
#Substraction

R1 = A - B
print(R1)

[2 8]


In [16]:
#Multiplication

S = [2]
R2 = S*A
print(R2)

[8 6]


In [26]:
#Dot Product

A = np.array([4, 3])
B = np.array([[2], [-5]])

R = np.multiply(A,B)
print(R)

[[  8   6]
 [-20 -15]]


In [45]:
#Property of Matrix
#indentity Matrix

C = np.eye(3, 3)
print(C)

#Zero Matrix
D = np.zeros([5, 5])
print(D)

E = np.full((3,3), 7)
print(E)

F = np.transpose(A)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]


In [46]:
#Transpose
G = np.transpose(E)
print(E)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
